### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Misk00** [Isaac20231231/send_msg#3]
[ERROR][2024-12-27 08:43:40][send_msg.py:198] - 处理消息时发生异常: string indices must be integers, not 'str' 

包括实例的几种格式都报错

{
"data_list":[
{
 "receiver_name": ["M"],
 "message": "发送消息",
 "group_name": []
}
]
}

**Comment by Misk00** [comment]
改完了，如果需要的话我PR

**Comment by Isaac20231231** [comment]
> 改完了，如果需要的话我PR

可以pr一下 我看看哦 感谢
